service: minpair-api-nltk-layer
provider:
  name: aws
layers:
  nltkCorpus:
    path: nltk
    name: NltkCorpus
    description: Nltk corpus data.
    compatibleRuntimes:
      - python3.7
resources:
  Outputs:
    NltkCorpusLambdaLayer:
      Value:
        Ref: NltkCorpusLambdaLayer
      Export:
        Name: NltkCorpusLambdaLayer
